//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReasonCodeExample.XPathInformation.VisualStudioIntegration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PackageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PackageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReasonCodeExample.XPathInformation.VisualStudioIntegration.PackageResources", typeof(PackageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results. Click to navigate..
        /// </summary>
        internal static string MultipleResultText {
            get {
                return ResourceManager.GetString("MultipleResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results..
        /// </summary>
        internal static string NoResultsText {
            get {
                return ResourceManager.GetString("NoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open XPath Runner.
        /// </summary>
        internal static string ShowXPathWorkbenchCommandText {
            get {
                return ResourceManager.GetString("ShowXPathWorkbenchCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} result. Click to navigate..
        /// </summary>
        internal static string SingleResultText {
            get {
                return ResourceManager.GetString("SingleResultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error evaluating XPath..
        /// </summary>
        internal static string XPathEvaluationErrorText {
            get {
                return ResourceManager.GetString("XPathEvaluationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error navigating to matching node..
        /// </summary>
        internal static string XPathWorkbenchNavigationErrorText {
            get {
                return ResourceManager.GetString("XPathWorkbenchNavigationErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string XPathWorkbenchNavigationErrorTitle {
            get {
                return ResourceManager.GetString("XPathWorkbenchNavigationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter XPath....
        /// </summary>
        internal static string XPathWorkbenchSearchWatermark {
            get {
                return ResourceManager.GetString("XPathWorkbenchSearchWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPath Information - Runner.
        /// </summary>
        internal static string XPathWorkbenchWindowTitle {
            get {
                return ResourceManager.GetString("XPathWorkbenchWindowTitle", resourceCulture);
            }
        }
    }
}
